#name of the workflow
name: My Second Manual Workflow
on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # set node.js 
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  
      
    # Cache dependency  
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
    # Install dependencies    
    - name: Install dependencies
      run: npm install
      
      # Build
    - name: Build
      run: npm run build
 
        
  #Upload it to Artifact
  #artifact:
    # The type of runner that the job will run on
   # runs-on: ubuntu-latest
    #name: Artifact
    #needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    #- uses: actions/checkout@v2
    # Runs a single command using the runners shell
    #- name: Send greeting
    #  run: echo "Hello .. I am in artifact"  
    #- uses: actions/checkout@master
    - name: Current timestamp
      id: timestamp
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')" 
      
   
    - name: Upload to S3
    #  uses: aws-actions/configure-aws-credentials@v1
      uses: jakejarvis/s3-sync-action@master
      #with:
       # args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1  
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
     
      
    - name: Generate package
      uses: thedoctor0/zip-release@master
      with:
        filename: 'package.zip'
        exclusions: '*.git* /*node_modules/* /*test/* *.md'
 
  Prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Prod
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # - uses: actions/checkout@v2
     - uses: jakejarvis/s3-sync-action@master
    # Runs a single command using the runners shell
     - name: Deploy to Prod
       run: aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/ s3://${{ secrets.AWS_S3_BUCKET }}/shashi
    
    

      
    
